### ISSUE TITLE
Cannot get JWT token

### ISSUE THREAD

**Issue by markociglar** [enr1c091/microservices-oauth#1]
Hi, 

I am trying to run auth-server standalone, without eureka. When i trigger POST method for token, I got empty response.
REQUEST:
curl -v POST http://localhost:9999/uaa/oauth/token -H 'Authorization: Basic YWRtaW5hcHA6cGFzc3dvcmQ=' -H 'Content-type: application/x-www-form-urlencoded' -d 'grant_type=password&username=admin&password=password'

Can you pls explain me, what am i doing wrong?
Thanks :)

**Comment by weskhaled** [comment]
Check your database tables is set ?

**Comment by markociglar** [comment]
I filled my database with data already. But I figure out what is wrong. My Authorization token was wrong (cliendId:secret). Thanks anyway 👍

**Comment by enr1c091** [comment]
Sorry for the delay and thanks weskhaled for following up. I'm marking this as closed assuming it's all good now :)
